###
# LIST CARD-TEMPLATES
GET {{ TENANT_BASE_URL }}/card-templates?limit=10 HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}


###
# CREATE PATTERN
POST {{ TENANT_BASE_URL }}/card-templates HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}

{
  "serial": "BINGO-CLASSIC-506",
  "layout": [
    [
      0,
      0,
      16
    ],
    [
      0,
      1,
      28
    ],
    [
      0,
      2,
      42
    ],
    [
      0,
      3,
      60
    ],
    [
      0,
      4,
      75
    ],
    [
      1,
      0,
      5
    ],
    [
      1,
      1,
      9
    ],
    [
      1,
      2,
      14
    ],
    [
      1,
      3,
      19
    ],
    [
      1,
      4,
      21
    ],
    [
      2,
      0,
      2
    ],
    [
      2,
      1,
      10
    ],
    [
      2,
      2,
      30
    ],
    [
      2,
      3,
      31
    ],
    [
      2,
      4,
      33
    ],
    [
      3,
      0,
      42
    ],
    [
      3,
      1,
      45
    ],
    [
      3,
      2,
      48
    ],
    [
      3,
      3,
      50
    ],
    [
      3,
      4,
      55
    ],
    [
      4,
      0,
      59
    ],
    [
      4,
      1,
      61
    ],
    [
      4,
      2,
      66
    ],
    [
      4,
      3,
      68
    ],
    [
      4,
      4,
      71
    ]
  ]
}


###
# RETRIEVE PATTERN
GET {{ TENANT_BASE_URL }}/card-templates/{{ cardTemplateId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}


###
# UPDATE PATTERN
PATCH {{ TENANT_BASE_URL }}/card-templates/{{ cardTemplateId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}

{
  "serial": "MOLS-2024-00223"
}


###
# DELETE PATTERN
DELETE {{ TENANT_BASE_URL }}/card-templates/{{ cardTemplateId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}


###
# sample data
OPTIONS {{ TENANT_BASE_URL }}/card-templates?search= HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}
[]