###
# LIST WINNERS
GET {{ TENANT_BASE_URL }}/games/{{ gameId }}/winners?search= HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}


###
# CREATE WINNER
POST {{ TENANT_BASE_URL }}/games/{{ gameId }}/winners HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}


###
# RETRIEVE WINNER
GET {{ TENANT_BASE_URL }}/games/{{ gameId }}/winners/{{ winnerId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}


###
# UPDATE WINNER
PATCH {{ TENANT_BASE_URL }}/games/{{ gameId }}/winners/{{ winnerId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}

{}


###
# DELETE WINNER
DELETE {{ TENANT_BASE_URL }}/games/{{ gameId }}/winners/{{ winnerId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}


###
# sample data
OPTIONS {{ TENANT_BASE_URL }}/games/{{ gameId }}/winners?search= HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}