###
# LIST PERMISSIONS
GET {{ TENANT_BASE_URL }}/permissions HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json


###
# RETRIEVE USER
GET {{ TENANT_BASE_URL }}/permissions/{{ permissionId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json


###
# UPDATE USER
PATCH {{ TENANT_BASE_URL }}/permissions/{{ permissionId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json

{
  "name": "Update User Status ."
}