###
# LIST ROLES
GET {{ TENANT_BASE_URL }}/roles?search= HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json


###
# CREATE ROLE
POST {{ TENANT_BASE_URL }}/roles HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json

{
  "name": "Cashier",
  "description": "control the in and out of cash (money)"
}


###
# RETRIEVE ROLE
GET {{ TENANT_BASE_URL }}/roles/{{ roleId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json


###
# UPDATE ROLE
PATCH {{ TENANT_BASE_URL }}/roles/{{ roleId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json

{
  "name": "Cashier"
}


###
# DELETE ROLE
DELETE {{ TENANT_BASE_URL }}/roles/{{ roleId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json


###
# ROLE PERMISSIONS
GET {{ TENANT_BASE_URL }}/roles/{{ roleId }}/permissions HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json


###
# ASSIGN PERMISSIONS FOR GIVEN ROLE
PATCH {{ TENANT_BASE_URL }}/roles/{{ roleId }}/role-permissions HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json

{
  ": [
    {
      "permissionId": "fb89a2c0-7129-4dc1-b4ad-c8e57e44c021",
      "isTemporary": false
    },
    {
      "permissionId": "3299760f-cf9e-4819-b1f7-7f6e6d250108",
      "isTemporary": false
    },
    {
      "permissionId": "f6116c8c-fbb4-4d0f-bf5d-acfa605f6671",
      "isTemporary": true
    }
  ]
}