###
# LIST USERS
GET {{ TENANT_BASE_URL }}/users?includeDeleted=true HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
Origin: http://test.localhost.test:5173/test


###
# CREATE USER
POST {{ TENANT_BASE_URL }}/users HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json

{
  "firstName": "samuel",
  "lastName": "zeray",
  "username": "samuel",
  "email": "samuel05@billing.saas.com",
  "password": "meles05",
  "password1": "meles05",
  "phone": "+251 98434 8348"
}


###
# RETRIEVE USER
GET {{ TENANT_BASE_URL }}/users/{{ userId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json


###
# UPDATE USER
PATCH {{ TENANT_BASE_URL }}/users/{{ userId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json

{
  "ast": "atte",
  "email": "saraBest.kebede@support.com"
}


###
# DELETE USER
DELETE {{ TENANT_BASE_URL }}/users/{{ userId }} HTTP/1.1
Authorization: Bearer {{ access }}
Content-Type: application/json
Origin: https://localhost:4000