###
# LIST SYSTEM-USERS
GET {{ SYSTEM_BASE_URL }}/system-users HTTP/1.1


###
# CREATE SYSTEM-USER
POST {{ SYSTEM_BASE_URL }}/system-users HTTP/1.1
content-type: application/json

{
  "firstName": "Yonas",
  "lastName": "Teklu",
  "username": "yonas.billing",
  "email": "yonas@billing.saas.com",
  "password": "Billing789@",
  "password1": "Billing789@",
  "roleId": "351e4169-9fa9-4eae-a228-8550603fd265"
}


###
# RETRIEVE SYSTEM-USER
GET {{ SYSTEM_BASE_URL }}/system-users/{{systemUserId}} HTTP/1.1


###
# UPDATE SYSTEM-USER
PATCH {{ SYSTEM_BASE_URL }}/system-users/{{systemUserId}} HTTP/1.1

{
    "ast": "atte",
    "email": "saraBest.kebede@support.com"
    "attributes": {
        "phone": "09978000669"
    }
}


###
# DELETE SYSTEM-USER
DELETE {{ SYSTEM_BASE_URL }}/system-users/{{systemUserId}} HTTP/1.1