###
# LIST TENANTS
GET {{ SYSTEM_BASE_URL }}/tenants HTTP/1.1


###
# ONBOARD NEW TENANT
POST {{ SYSTEM_BASE_URL }}/tenants HTTP/1.1
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}

{
  "subdomain": "beza-burger",
  "name": "beza berger house",
  "pricingPlanId": "{{ pricingPlanId }}",
  "billingCycle": "yearly",
  "firstName": "meles",
  "lastName": "haileselassie",
  "username": "admin",
  "email": "meleshaileselassie05@gmail.com",
  "password": "meles05",
  "password1": "meles05"
}


###
# RETRIEVE TENANT
GET {{ SYSTEM_BASE_URL }}/tenants/{{tenantId}} HTTP/1.1


###
# UPDATE TENANT
PATCH {{ SYSTEM_BASE_URL }}/tenants/{{tenantId}} HTTP/1.1
Content-Type: application/json
X-Tenant-Subdomain: {{ subdomain }}
X-Tenant-ID: {{ tenantId }}

{
  "subdomain": "beza-burger"
}


###
# DELETE TENANT
DELETE {{ SYSTEM_BASE_URL }}/tenants/{{tenantId}} HTTP/1.1